#!/bin/bash

export HUBOT_HIPCHAT_JID=''
export HUBOT_HIPCHAT_PASSWORD=''
export HUBOT_HIPCHAT_ROOMS=''
export HUBOT_HIPCHAT_TOKEN=''
export HUBOT_HIPCHAT_NAME=''
export HUBOT_PAGERDUTY_API_KEY=''
export HUBOT_PAGERDUTY_SUBDOMAIN=''
export HUBOT_PAGERDUTY_SERVICE_API_KEY=''
export HUBOT_PAGERDUTY_SCHEDULE_ID=''
export HUBOT_MEMEGENERATOR_USERNAME=''
export HUBOT_MEMEGENERATOR_PASSWORD=''
export HUBOT_PULL_REQUEST_PAGINATION_BORDER=''
export HUBOT_PULL_REQUEST_PAGINATION_PER_PAGE=''

/etc/init.d/redis-server start 
bin/hubot --adapter hipchat
